spring.application.name=animelist

# database urls
spring.datasource.url=jdbc:postgresql://ep-aged-recipe-ac5efbil-pooler.sa-east-1.aws.neon.tech/neondb?&sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_FRx6XK8fZtID
spring.datasource.driver-class-name=org.postgresql.Driver

# config JPA / hibernate
spring.jpa.hibernate.ddl-auto=update

# logs
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect